spring:
  servlet:
    multipart:
      max-file-size: 10MB  # 업로드 파일의 최대 크기 설정 (예: 10MB)
      max-request-size: 10MB  # 요청의 최대 크기 설정 (예: 10MB)
  data:
    elasticsearch:
      cluster-name: my-cluster
      cluster-nodes: localhost:9200

#  h2:
#    console.enabled: true

#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#    initialization-mode: always

#  jpa:
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create
#    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/penterest?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Abcd123@
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      show-sql: true

jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
  # echo 'jsh-springboot-and-jwt-tutorial-this-is-for-generating-jwt-secretkey-base64'|base64
  secret: anNoLXNwcmluZ2Jvb3QtYW5kLWp3dC10dXRvcmlhbC10aGlzLWlzLWZvci1nZW5lcmF0aW5nLWp3dC1zZWNyZXRrZXktYmFzZTY0Cg
  token-validity-in-seconds: 86400

logging:
  level:
    org:
      springframework:
        security: DEBUG
